### ISSUE TITLE
github-issue-refresh is broken! 

### ISSUE THREAD

**Issue by robbyoconnor** [inkel/github-issues.el#7]
Refreshing details of individual github issues is broken currently. 
Reproduce: 
* Open an issue buffer 
* try to refresh it, 

Output from my `Messages` buffer
```
if: Cyclic keymap inheritance
```

It is very likely the bug could be coming from spacemacs...not sure. But triggering the command manually causes the same error, so I suspect github-issues.el is to blame. 

System info: 
- OS: gnu/linux
- Emacs: 24.4.1

**Comment by Silex** [comment]
I think this is fixed now, please reopen if it's not.
